
import { Inter } from 'next/font/google'
import 'bootstrap/dist/css/bootstrap.min.css';
import './globals.css'
import App from '@/components/App';

import { StoreProvider } from '@/redux/StoreProvider';








const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Acme Store',
  description: 'Generated by create next app',
}

export default function RootLayout({ children  }) {

 
  

  
  return (
    <html lang="en">
     
      <body className={inter.className}>
        <StoreProvider>
            <App>{children}</App>
        </StoreProvider>
      </body>
    </html>
  )
}


