
import { Inter } from 'next/font/google'
import 'bootstrap/dist/css/bootstrap.min.css';
import BootsrapClient from '@/components/BootsrapClient';
import './globals.css'
import Header from '@/components/header'
import Footer from '@/components/footer'







const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Acme Store',
  description: 'Generated by create next app',
}

export default function RootLayout({ children  }) {

 
  

  
  return (
    <html lang="en">
     
      <body className={inter.className}>


        <Header /> 
        {children}

        <BootsrapClient />

        <Footer />
      
      </body>
    </html>
  )
}


